version: "3.8"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - web
      - observability

  frontend:
    image: watcherdevx/multi-fintech-dashboard:v1
    container_name: frontend
    restart: unless-stopped
    env_file:
      - ./.env.frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - web
      - observability

  backend:
    image: watcherdevx/multi-fintech-backend:latest
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./.env.backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - web
      - observability

volumes:
  caddy_data:
  caddy_config:

networks:
  web:
    driver: bridge
  observability:
    driver: bridge
